export const JURISDICTIONS = {
  DE: "DE", AT: "AT", CH: "CH", LI: "LI",
  LU: "LU", SE: "SE", NO: "NO", DK: "DK", FI: "FI", US: "US",
};

export const JURISDICTION_META = {
  DE: { flag: "🇩🇪", name: { DE: "Deutschland", EN: "Germany", FR: "Allemagne" }, system: "ZPO / BGB / StPO", currency: "€" },
  AT: { flag: "🇦🇹", name: { DE: "Österreich", EN: "Austria", FR: "Autriche" }, system: "ZPO / ABGB / StPO", currency: "€" },
  CH: { flag: "🇨🇭", name: { DE: "Schweiz", EN: "Switzerland", FR: "Suisse" }, system: "ZPO / OR / ZGB", currency: "CHF" },
  LI: { flag: "🇱🇮", name: { DE: "Liechtenstein", EN: "Liechtenstein", FR: "Liechtenstein" }, system: "ZPO / PGR", currency: "CHF" },
  LU: { flag: "🇱🇺", name: { DE: "Luxemburg", EN: "Luxembourg", FR: "Luxembourg" }, system: "Code de procédure civile", currency: "€" },
  SE: { flag: "🇸🇪", name: { DE: "Schweden", EN: "Sweden", FR: "Suède" }, system: "Rättegångsbalken", currency: "SEK" },
  NO: { flag: "🇳🇴", name: { DE: "Norwegen", EN: "Norway", FR: "Norvège" }, system: "Tvisteloven", currency: "NOK" },
  DK: { flag: "🇩🇰", name: { DE: "Dänemark", EN: "Denmark", FR: "Danemark" }, system: "Retsplejeloven", currency: "DKK" },
  FI: { flag: "🇫🇮", name: { DE: "Finnland", EN: "Finland", FR: "Finlande" }, system: "Oikeudenkäymiskaari", currency: "€" },
  US: { flag: "🇺🇸", name: { DE: "USA", EN: "United States", FR: "États-Unis" }, system: "Common Law / FRCP", currency: "$" },
};

export function getAIContext(jurisdiction, usState) {
  const contexts = {
    DE: `You are an expert German attorney. Apply German law strictly: ZPO, BGB, StGB, HGB. Reference specific paragraphs (§§). Follow BGH and BVerfG case law. Use precise German legal terminology.`,
    AT: `You are an expert Austrian attorney. Apply Austrian law: ZPO, ABGB, StGB. Reference OGH decisions. Distinguish from German law where relevant. Use Austrian legal terminology.`,
    CH: `You are an expert Swiss attorney. Apply Swiss law: ZPO, OR, ZGB, StGB. Reference BGer/Tribunal fédéral decisions. Note cantonal variations where relevant.`,
    LI: `You are an expert Liechtenstein attorney. Apply Liechtenstein law including the PGR (Personen- und Gesellschaftsrecht). Note similarities to Austrian law.`,
    LU: `You are an expert Luxembourg attorney. Apply Luxembourg law based on French civil law tradition. Reference Cour d'appel and Cour de cassation decisions. Note EU law primacy.`,
    SE: `You are an expert Swedish attorney. Apply Swedish law under the Rättegångsbalken. Reference Högsta domstolen decisions. Note Nordic legal tradition.`,
    NO: `You are an expert Norwegian attorney. Apply Norwegian law under the Tvisteloven. Reference Høyesterett decisions.`,
    DK: `You are an expert Danish attorney. Apply Danish law under the Retsplejeloven. Reference Højesteret decisions.`,
    FI: `You are an expert Finnish attorney. Apply Finnish law under the Oikeudenkäymiskaari. Reference Korkein oikeus decisions. Note bilingual (Finnish/Swedish) legal system.`,
    US: `You are an expert American attorney${usState ? ` specializing in ${usState} law` : ""}. Apply US federal and ${usState || "state"} law. Reference FRCP, applicable federal statutes, ${usState ? `${usState} Rules of Civil Procedure, ` : ""}and relevant case law. Use IRAC structure.`,
  };
  return contexts[jurisdiction] || contexts.DE;
}

const DE_TEXT = {
  // Platform
  platform: "Ihre KI-gestützte Rechtsplattform",
  platformSub: "Strategische Fallanalyse & Intelligente Prozessführung",
  copyright: "© 2026 MachiavelLEX · Alle Rechte vorbehalten",
  dsgvo: "DSGVO-konform · EU-Server",

  // KI-Analyse
  kiFallanalyse: "KI-Fallanalyse",
  analyseStarten: "KI-Analyse starten",
  analyseWarning: "Diese Analyse ist eine KI-gestützte Einschätzung und ersetzt keine Rechtsberatung.",
  fallAuswaehlen: "Fall auswählen",

  // KPI Labels
  aktiveFaelleLabel: "Aktive Fälle",
  offeeneFristenLabel: "Offene Fristen",
  avgPrognoseLabel: "Ø Prognose",
  argumenteLabel: "Argumente",

  // Charts
  faelleNachRechtsgebiet: "Fälle nach Rechtsgebiet",
  statusVerteilung: "Status-Verteilung",
  prognoseVerteilung: "Prognose-Verteilung",
  fristenUebersicht: "Fristen-Übersicht",
  naechste14Tage: "Nächste 14 Tage",
  instanzVerteilung: "Instanz-Verteilung",
  risikoverteilung: "Risikoverteilung",
  rechtsgebiet: "Rechtsgebiet",
  gericht: "Gericht",
  instanz: "Instanz",
  aktiv: "Status",
  streitwert: "Streitwert",
  prognose: "Prognose",

  // General
  noDataLabel: "Keine Daten",
  noDeadlinesRecorded: "Keine Fristen erfasst",
  noUpcomingDeadlines: "Keine bevorstehenden Fristen",
  loading: "Laden…",
  saveBtn: "Speichern",
  cancelBtn: "Abbrechen",
  updateBtn: "Aktualisieren",
  createBtn: "Erstellen",
  backLabel: "Zurück",
  searchPlaceholder: "Suchen…",
  todayLabel: "Heute",
  tomorrowLabel: "Morgen",
  daysOverdueLabel: (n) => `${n}d überfällig`,
  inDaysLabel: (n) => `in ${n} Tagen`,

  // Shared subtitle helpers
  mandatesSub: (total, active) => `${total} Mandate · ${active} aktiv`,
  ofTotalLabel: (n) => `von ${n} gesamt`,
  winProbabilityLabel: "Erfolgswahrscheinlichkeit",
  totalRecordedLabel: "gesamt erfasst",
  filterResetBtn: "Zurücksetzen",
  noDataShort: "Keine Daten",
  noDeadlinesShort: "Keine Fristen erfasst",
  todayShort: "Heute",
  noUpcomingShort: "Keine bevorstehenden Fristen",

  // FallAssistentChat
  conversationLabel: "Gespräch",
  lexTitle: "Lex · Fall-Assistent",
  lexDescription: "Ich kann Fälle analysieren, Fristen überwachen, Argumente verwalten und strategische Empfehlungen geben.",
  newConversationBtn: "Neues Gespräch",
  loadingLabel: "Lädt…",
  noConversationsYet: "Noch keine Gespräche",
  chatInputPlaceholder: "Juristische Frage stellen oder Fall-Daten verwalten…",
  quickPrompts: [
    "Zeige mir alle offenen Fristen",
    "Analysiere meinen stärksten Fall",
    "Welche Argumente fehlen noch?",
    "Gib mir eine Risikoübersicht",
  ],

  // LexaraDashboard
  caseOverview: "Fallübersicht",
  mandatesTotalSub: (total, active) => `${total} Mandate · ${active} aktiv`,
  searchCase: "Fall suchen…",
  newCase: "Neuer Fall",
  createCaseTitle: "Neuen Fall anlegen",
  caseNamePlaceholder: "Fallname *",
  fileNumberPlaceholder: "Aktenzeichen",
  legalAreaPlaceholder: "Rechtsgebiet",
  createButton: "Fall erstellen",
  progressLabel: "Fortschritt",
  stepsLabel: "Schritte",
  argsLabel: "Args",
  evidenceLabel: "Beweise",
  personsLabel: "Personen",
  deadlinesLabel: "Fristen",
  noCasesTitle: "Noch keine Fälle",
  noCasesSubtitle: 'Klicke auf „Neuer Fall“ um zu beginnen',
  statusOptions: ["Aktiv", "Vorbereitung", "Abgeschlossen", "Ruhend"],
  instanzOptions: ["Erstinstanz", "Berufung", "Revision"],

  // KanzleiCockpit
  cockpitTitle: "Kanzlei-Cockpit",
  portfolioSub: (n) => `Portfolio-Übersicht · ${n} Mandate`,
  newCaseLinkLabel: "+ Neuer Fall",
  totalClaimLabel: "Gesamtstreitwert",
  allMandatesSub: "alle Mandate",
  avgPrognosisLabel: "Ø Erfolgsprognose",
  weightedAvgSub: "gewichteter Durchschnitt",
  overdueDeadlinesLabel: "überfällig",
  actNow: "Sofort handeln",
  allOnTrack: "Alles im Plan",
  highRiskLabel: "Hochrisiko-Fälle (aktiv)",
  noHighRisk: "Keine Hochrisiko-Fälle aktiv ✓",
  topChancesLabel: "Top-Chancen (aktiv)",
  noTopChancesText: "Noch keine Fälle mit hoher Prognose",
  nextDeadlinesLabel: "Nächste Fristen",
  showAllLink: "Alle anzeigen →",
  noOpenDeadlinesText: "Keine offenen Fristen ✓",
  allMandatesLabel: "Alle Mandate",
  entriesLabel: (n) => `${n} Einträge`,
  tableHeaderCase: "Fall",
  tableHeaderCourt: "Gericht",
  tableHeaderClaimValue: "Streitwert",
  tableHeaderStatus: "Status",
  casesLabelShort: "Fälle",

  // RichterProfile
  judgeProfilesTitle: "Richterprofile",
  profilesSub: (n) => `${n} Profile · Erfahrungen & KI-Taktikanalyse`,
  addJudgeBtn: "+ Richter",
  editProfileTitle: "Profil bearbeiten",
  newProfileTitle: "Neues Richterprofil",
  namePlaceholder: "Name *",
  courtPlaceholder: "Gericht *",
  chamberPlaceholder: "Kammer / Senat",
  plaintiffRateLabel: "Klägerquote %",
  settlementRateLabel: "Vergleichsrate %",
  avgDurationLabel: "Ø Dauer (Mo.)",
  totalRulingsLabel: "Urteile gesamt",
  knownForPlaceholder: "Bekannt für...",
  notesPlaceholder: "Notizen",
  linkToCase: "Mit Fall verknüpfen",
  selectCasePlaceholder: "Fall auswählen...",
  detailsAI: "Details & KI",
  noProfilesTitle: "Noch keine Richterprofile",
  noProfilesSub: "Klicken Sie auf \"+ Richter\" um ein Profil anzulegen",
  plaintiffRateBar: "Klägerquote",
  settlementRateBar: "Vergleichsrate",
  avgMonthsSuffix: "Mo. Ø",
  rulingsLabelShort: "Urteile",
  experiencesLabelShort: "Erfahrungen",
  kiAnalysisExists: "✓ KI-Analyse vorhanden",

  // RichterDetail
  backToOverview: "Zurück zur Übersicht",
  experiencesSection: "Kanzlei-Erfahrungen",
  addExperience: "Erfahrung",
  dateLabel: "Datum",
  authorLabel: "Autor / Anwalt",
  caseContextLabel: "Fallkontext (optional)",
  settlementReadiness: "Vergleichsbereitschaft",
  decisionSpeed: "Entscheidungsgeschwindigkeit",
  expertiseLabel: "Sachkompetenz",
  experienceReport: "Erfahrungsbericht *",
  noExperiencesYet: "Noch keine Erfahrungen dokumentiert.",
  addFirstExperience: "Fügen Sie die erste Erfahrung hinzu.",
  kiTacticsTitle: "KI-Taktikanalyse",
  reanalyzeBtn: "Neu analysieren",
  startAnalysisBtn: "Analyse starten",
  analyzingBtn: "Analysiere...",
  kiAnalysisHint: "Starten Sie die KI-Analyse um taktische Empfehlungen auf Basis des Profils und der Kanzlei-Erfahrungen zu erhalten.",
  lastAnalysis: "Letzte Analyse",
  kiCreditWarning: "⚠️ Diese Analyse verwendet Gemini Pro mit Internetsuche (mehr KI-Credits)",
  summaryLabel: "📊 Zusammenfassung",
  foundRulingsLabel: "🔍 Gefundene Urteile & Entscheidungen",
  argumentationPatternsLabel: "🧠 Typische Argumentationsmuster",
  preferredNormsLabel: "§ Bevorzugte Rechtsnormen",
  argumentStanceLabel: "⚖️ Haltung zu Argumenttypen",
  preferredMotionsLabel: "📋 Bevorzugte Antragstypen",
  damageRangeLabel: "💶 Schadensersatz / Urteilsbandbreite",
  evidenceHandlingLabel: "📜 Umgang mit Beweismitteln",
  plaintiffStrengthsLabel: "✅ Stärken für Kläger",
  plaintiffRisksLabel: "⚠️ Risiken für Kläger",
  doLabel: "👍 DO",
  dontLabel: "👎 DON'T",
  tacticalTipsLabel: "💡 Verhandlungstipps",
  settlementStrategyLabel: "🤝 Vergleichsstrategie",
  timingLabel: "⏰ Timing",
  overallAssessmentLabel: "🎯 Gesamteinschätzung",
  anonLabel: "Anonym",
  settlementBar: "Vergleich",
  speedBar: "Geschwindigkeit",
  resultLabel: "Ergebnis",
  sourceLabel: "Quelle",
  parametersLabel: "Parameter",
  successRateLabel: "Erfolgsrate",
  typicalRangeLabel: "Typischer Bereich",
  factorsLabel: "Einflussfaktoren",
  specialFeaturesLabel: "Besonderheiten",
  stanceLabel: "Haltung",
  reasonLabel: "Begründung",

  // Zeitleiste
  timelineTitle: "Fristen-Zeitleiste",
  iCalExport: "iCal exportieren",
  filterAll: "Alle",
  filterOpen: "Offen",
  filterCritical: "⚠ Kritisch",
  filterCompleted: "Erledigt",
  noDeadlinesFound: "Keine Fristen gefunden",
  openStatusLabel: "offen",
  criticalStatusLabel: "kritisch (≤14 Tage)",
  doneStatus: "Erledigt",
  missedStatus: "Versäumt",

  // PlattformAgent
  newSession: "+ Neue Sitzung",
  sessionsLabel: "Sitzungen",
  noSessionsYet: "Noch keine Sitzungen",
  platformAgentTitle: "Plattform-Optimierer",
  platformAgentDesc: "Der KI-Agent analysiert Ihre Kanzleidaten, identifiziert Lücken und setzt Verbesserungen direkt um – bis MachiavelLEX für Großkanzleien unverzichtbar ist.",
  nextTaskPlaceholder: "Nächste Aufgabe für den Agenten…",
  customTaskPlaceholder: "Eigene Aufgabe eingeben…",
  agentNote: "Der Agent kann Richterprofile, Argumente und Fristen direkt erstellen & bearbeiten.",

  module: [
    { category: "KI-Assistent", title: "Fall-Assistent Chat", description: "Konversationelle KI-Analyse Ihrer Mandate" },
    { category: "Mandatsverwaltung", title: "Lexara Dashboard", description: "Alle Fälle im Überblick – Fristen, Argumente, Beweise" },
    { category: "Personenprofile", title: "Richterprofile", description: "Erfahrungen, Statistiken & KI-Taktikanalyse" },
    { category: "KI-Agent", title: "Plattform-Agent", description: "Autonomer Agent für Plattformoptimierung und Analyse" },
    { category: "Cockpit", title: "Kanzlei-Cockpit", description: "Risiko-Ampel, Portfolio und Fristen-Monitoring" },
    { category: "Analytics", title: "Kanzlei-Analytik", description: "Visualisierung aller Fallkennzahlen und Trends" },
    { category: "Strategie & Psycho-Analyse", title: "Sun Tzu × Machiavelli", description: "48 Laws of Power · Strategischer Pfad & Risikobewertung für Ihren Fall" },
  ],
};

const EN_TEXT = {
  // Platform
  platform: "Your AI-Powered Legal Platform",
  platformSub: "Strategic Case Analysis & Intelligent Litigation Management",
  copyright: "© 2026 MachiavelLEX · All rights reserved",
  dsgvo: "GDPR-compliant · EU Servers",

  // KI-Analyse
  kiFallanalyse: "AI Case Analysis",
  analyseStarten: "Start AI Analysis",
  analyseWarning: "This analysis is AI-assisted and does not constitute legal advice.",
  fallAuswaehlen: "Select case",

  // KPI Labels
  aktiveFaelleLabel: "Active Cases",
  offeeneFristenLabel: "Open Deadlines",
  avgPrognoseLabel: "Avg. Prognosis",
  argumenteLabel: "Arguments",

  // Charts
  faelleNachRechtsgebiet: "Cases by Practice Area",
  statusVerteilung: "Status Distribution",
  prognoseVerteilung: "Prognosis Distribution",
  fristenUebersicht: "Deadline Overview",
  naechste14Tage: "Next 14 Days",
  instanzVerteilung: "Court Level Distribution",
  risikoverteilung: "Risk Distribution",
  rechtsgebiet: "Practice Area",
  gericht: "Court",
  instanz: "Court Level",
  aktiv: "Status",
  streitwert: "Amount in Controversy",
  prognose: "Win Probability",

  // General
  noDataLabel: "No data available",
  noDeadlinesRecorded: "No deadlines recorded",
  noUpcomingDeadlines: "No upcoming deadlines",
  loading: "Loading…",
  saveBtn: "Save",
  cancelBtn: "Cancel",
  updateBtn: "Update",
  createBtn: "Create",
  backLabel: "Back",
  searchPlaceholder: "Search…",
  todayLabel: "Today",
  tomorrowLabel: "Tomorrow",
  daysOverdueLabel: (n) => `${n}d overdue`,
  inDaysLabel: (n) => `in ${n} days`,

  // Shared subtitle helpers
  mandatesSub: (total, active) => `${total} matters · ${active} active`,
  ofTotalLabel: (n) => `of ${n} total`,
  winProbabilityLabel: "Win Probability",
  totalRecordedLabel: "total recorded",
  filterResetBtn: "Reset",
  noDataShort: "No data",
  noDeadlinesShort: "No deadlines recorded",
  todayShort: "Today",
  noUpcomingShort: "No upcoming deadlines",

  // FallAssistentChat
  conversationLabel: "Conversation",
  lexTitle: "Lex · Case Assistant",
  lexDescription: "I can analyze cases, monitor deadlines, manage arguments and provide strategic recommendations.",
  newConversationBtn: "New Conversation",
  loadingLabel: "Loading…",
  noConversationsYet: "No conversations yet",
  chatInputPlaceholder: "Ask a legal question or manage case data…",
  quickPrompts: [
    "Show me all open deadlines",
    "Analyze my strongest case",
    "Which arguments are missing?",
    "Give me a risk overview",
  ],

  // LexaraDashboard
  caseOverview: "Case Overview",
  mandatesTotalSub: (total, active) => `${total} matters · ${active} active`,
  searchCase: "Search cases…",
  newCase: "New Case",
  createCaseTitle: "Create New Case",
  caseNamePlaceholder: "Case name *",
  fileNumberPlaceholder: "File number",
  legalAreaPlaceholder: "Practice area",
  createButton: "Create Case",
  progressLabel: "Progress",
  stepsLabel: "steps",
  argsLabel: "Args",
  evidenceLabel: "Evidence",
  personsLabel: "Persons",
  deadlinesLabel: "Deadlines",
  noCasesTitle: "No cases yet",
  noCasesSubtitle: "Click \"New Case\" to get started",
  statusOptions: ["Aktiv", "Vorbereitung", "Abgeschlossen", "Ruhend"],
  instanzOptions: ["Erstinstanz", "Berufung", "Revision"],

  // KanzleiCockpit
  cockpitTitle: "Firm Cockpit",
  portfolioSub: (n) => `Portfolio Overview · ${n} matters`,
  newCaseLinkLabel: "+ New Case",
  totalClaimLabel: "Total Claim Value",
  allMandatesSub: "all matters",
  avgPrognosisLabel: "Avg. Win Probability",
  weightedAvgSub: "weighted average",
  overdueDeadlinesLabel: "overdue",
  actNow: "Act immediately",
  allOnTrack: "All on track",
  highRiskLabel: "High-Risk Cases (active)",
  noHighRisk: "No high-risk cases active ✓",
  topChancesLabel: "Top Opportunities (active)",
  noTopChancesText: "No cases with high prognosis yet",
  nextDeadlinesLabel: "Upcoming Deadlines",
  showAllLink: "View all →",
  noOpenDeadlinesText: "No open deadlines ✓",
  allMandatesLabel: "All Matters",
  entriesLabel: (n) => `${n} entries`,
  tableHeaderCase: "Case",
  tableHeaderCourt: "Court",
  tableHeaderClaimValue: "Claim Value",
  tableHeaderStatus: "Status",
  casesLabelShort: "Cases",

  // RichterProfile
  judgeProfilesTitle: "Judge Profiles",
  profilesSub: (n) => `${n} profiles · Experience & AI Tactical Analysis`,
  addJudgeBtn: "+ Judge",
  editProfileTitle: "Edit Profile",
  newProfileTitle: "New Judge Profile",
  namePlaceholder: "Name *",
  courtPlaceholder: "Court *",
  chamberPlaceholder: "Chamber / Panel",
  plaintiffRateLabel: "Plaintiff Rate %",
  settlementRateLabel: "Settlement Rate %",
  avgDurationLabel: "Avg. Duration (mo.)",
  totalRulingsLabel: "Total Rulings",
  knownForPlaceholder: "Known for...",
  notesPlaceholder: "Notes",
  linkToCase: "Link to case",
  selectCasePlaceholder: "Select case...",
  detailsAI: "Details & AI",
  noProfilesTitle: "No judge profiles yet",
  noProfilesSub: "Click \"+ Judge\" to create a profile",
  plaintiffRateBar: "Plaintiff Rate",
  settlementRateBar: "Settlement Rate",
  avgMonthsSuffix: "mo. avg.",
  rulingsLabelShort: "Rulings",
  experiencesLabelShort: "Experiences",
  kiAnalysisExists: "✓ AI Analysis available",

  // RichterDetail
  backToOverview: "Back to overview",
  experiencesSection: "Firm Experiences",
  addExperience: "Experience",
  dateLabel: "Date",
  authorLabel: "Author / Attorney",
  caseContextLabel: "Case context (optional)",
  settlementReadiness: "Settlement Readiness",
  decisionSpeed: "Decision Speed",
  expertiseLabel: "Expertise",
  experienceReport: "Experience Report *",
  noExperiencesYet: "No experiences documented yet.",
  addFirstExperience: "Add the first experience.",
  kiTacticsTitle: "AI Tactical Analysis",
  reanalyzeBtn: "Re-analyze",
  startAnalysisBtn: "Start Analysis",
  analyzingBtn: "Analyzing...",
  kiAnalysisHint: "Start the AI analysis to receive tactical recommendations based on the profile and firm experiences.",
  lastAnalysis: "Last analysis",
  kiCreditWarning: "⚠️ This analysis uses Gemini Pro with internet search (more AI credits)",
  summaryLabel: "📊 Summary",
  foundRulingsLabel: "🔍 Found Rulings & Decisions",
  argumentationPatternsLabel: "🧠 Typical Argumentation Patterns",
  preferredNormsLabel: "§ Preferred Legal Norms",
  argumentStanceLabel: "⚖️ Stance on Argument Types",
  preferredMotionsLabel: "📋 Preferred Motion Types",
  damageRangeLabel: "💶 Damage Award / Ruling Range",
  evidenceHandlingLabel: "📜 Evidence Handling",
  plaintiffStrengthsLabel: "✅ Strengths for Plaintiff",
  plaintiffRisksLabel: "⚠️ Risks for Plaintiff",
  doLabel: "👍 DO",
  dontLabel: "👎 DON'T",
  tacticalTipsLabel: "💡 Tactical Tips",
  settlementStrategyLabel: "🤝 Settlement Strategy",
  timingLabel: "⏰ Timing",
  overallAssessmentLabel: "🎯 Overall Assessment",
  anonLabel: "Anonymous",
  settlementBar: "Settlement",
  speedBar: "Speed",
  resultLabel: "Outcome",
  sourceLabel: "Source",
  parametersLabel: "Parameters",
  successRateLabel: "Success Rate",
  typicalRangeLabel: "Typical Range",
  factorsLabel: "Influencing Factors",
  specialFeaturesLabel: "Special Features",
  stanceLabel: "Stance",
  reasonLabel: "Reasoning",

  // Zeitleiste
  timelineTitle: "Deadline Timeline",
  iCalExport: "Export iCal",
  filterAll: "All",
  filterOpen: "Open",
  filterCritical: "⚠ Critical",
  filterCompleted: "Completed",
  noDeadlinesFound: "No deadlines found",
  openStatusLabel: "open",
  criticalStatusLabel: "critical (≤14 days)",
  doneStatus: "Completed",
  missedStatus: "Missed",

  // PlattformAgent
  newSession: "+ New Session",
  sessionsLabel: "Sessions",
  noSessionsYet: "No sessions yet",
  platformAgentTitle: "Platform Optimizer",
  platformAgentDesc: "The AI agent analyzes your firm data, identifies gaps and implements improvements directly – making MachiavelLEX indispensable for large law firms.",
  nextTaskPlaceholder: "Next task for the agent…",
  customTaskPlaceholder: "Enter custom task…",
  agentNote: "The agent can create & edit judge profiles, arguments and deadlines directly.",

  module: [
    { category: "AI Assistant", title: "Case Assistant Chat", description: "Conversational AI analysis of your cases" },
    { category: "Case Management", title: "Lexara Dashboard", description: "All cases at a glance – deadlines, arguments, evidence" },
    { category: "People Profiles", title: "Judge Profiles", description: "Experience, statistics & AI tactical analysis" },
    { category: "AI Agent", title: "Platform Agent", description: "Autonomous agent for platform optimization" },
    { category: "Cockpit", title: "Firm Cockpit", description: "Risk indicators, portfolio and deadline monitoring" },
    { category: "Analytics", title: "Firm Analytics", description: "Visualization of all case metrics and trends" },
    { category: "Strategy & Psycho-Analysis", title: "Sun Tzu × Machiavelli", description: "48 Laws of Power · Strategic path & risk assessment for your case" },
  ],
};

const FR_TEXT = {
  // Platform
  platform: "Votre plateforme juridique IA",
  platformSub: "Analyse stratégique des dossiers & gestion intelligente du contentieux",
  copyright: "© 2026 MachiavelLEX · Tous droits réservés",
  dsgvo: "Conforme RGPD · Serveurs UE",

  // KI-Analyse
  kiFallanalyse: "Analyse IA du dossier",
  analyseStarten: "Lancer l'analyse IA",
  analyseWarning: "Cette analyse est assistée par IA et ne constitue pas un avis juridique.",
  fallAuswaehlen: "Sélectionner un dossier",

  // KPI Labels
  aktiveFaelleLabel: "Dossiers actifs",
  offeeneFristenLabel: "Délais ouverts",
  avgPrognoseLabel: "Pronostic moy.",
  argumenteLabel: "Arguments",

  // Charts
  faelleNachRechtsgebiet: "Dossiers par domaine",
  statusVerteilung: "Répartition des statuts",
  prognoseVerteilung: "Répartition du pronostic",
  fristenUebersicht: "Vue d'ensemble des délais",
  naechste14Tage: "14 prochains jours",
  instanzVerteilung: "Répartition par instance",
  risikoverteilung: "Répartition des risques",
  rechtsgebiet: "Domaine juridique",
  gericht: "Tribunal",
  instanz: "Instance",
  aktiv: "Statut",
  streitwert: "Valeur du litige",
  prognose: "Pronostic",

  // General
  noDataLabel: "Aucune donnée",
  noDeadlinesRecorded: "Aucun délai enregistré",
  noUpcomingDeadlines: "Aucun délai à venir",
  loading: "Chargement…",
  saveBtn: "Enregistrer",
  cancelBtn: "Annuler",
  updateBtn: "Mettre à jour",
  createBtn: "Créer",
  backLabel: "Retour",
  searchPlaceholder: "Rechercher…",
  todayLabel: "Aujourd'hui",
  tomorrowLabel: "Demain",
  daysOverdueLabel: (n) => `${n}j en retard`,
  inDaysLabel: (n) => `dans ${n} jours`,

  // Shared subtitle helpers
  mandatesSub: (total, active) => `${total} dossiers · ${active} actifs`,
  ofTotalLabel: (n) => `sur ${n} au total`,
  winProbabilityLabel: "Probabilité de succès",
  totalRecordedLabel: "enregistrés au total",
  filterResetBtn: "Réinitialiser",
  noDataShort: "Aucune donnée",
  noDeadlinesShort: "Aucun délai enregistré",
  todayShort: "Aujourd'hui",
  noUpcomingShort: "Aucun délai à venir",

  // FallAssistentChat
  conversationLabel: "Conversation",
  lexTitle: "Lex · Assistant dossier",
  lexDescription: "Je peux analyser des dossiers, surveiller les délais, gérer les arguments et fournir des recommandations stratégiques.",
  newConversationBtn: "Nouvelle conversation",
  loadingLabel: "Chargement…",
  noConversationsYet: "Aucune conversation",
  chatInputPlaceholder: "Posez une question juridique ou gérez vos données de dossier…",
  quickPrompts: [
    "Montrez-moi tous les délais ouverts",
    "Analysez mon dossier le plus solide",
    "Quels arguments manquent encore ?",
    "Donnez-moi un aperçu des risques",
  ],

  // LexaraDashboard
  caseOverview: "Vue d'ensemble des dossiers",
  mandatesTotalSub: (total, active) => `${total} dossiers · ${active} actifs`,
  searchCase: "Rechercher un dossier…",
  newCase: "Nouveau dossier",
  createCaseTitle: "Créer un nouveau dossier",
  caseNamePlaceholder: "Nom du dossier *",
  fileNumberPlaceholder: "Référence",
  legalAreaPlaceholder: "Domaine juridique",
  createButton: "Créer le dossier",
  progressLabel: "Progression",
  stepsLabel: "étapes",
  argsLabel: "Args",
  evidenceLabel: "Preuves",
  personsLabel: "Personnes",
  deadlinesLabel: "Délais",
  noCasesTitle: "Aucun dossier",
  noCasesSubtitle: "Cliquez sur « Nouveau dossier » pour commencer",
  statusOptions: ["Aktiv", "Vorbereitung", "Abgeschlossen", "Ruhend"],
  instanzOptions: ["Erstinstanz", "Berufung", "Revision"],

  // KanzleiCockpit
  cockpitTitle: "Tableau de bord cabinet",
  portfolioSub: (n) => `Vue d'ensemble · ${n} dossiers`,
  newCaseLinkLabel: "+ Nouveau dossier",
  totalClaimLabel: "Valeur totale du litige",
  allMandatesSub: "tous dossiers",
  avgPrognosisLabel: "Pronostic moy. de succès",
  weightedAvgSub: "moyenne pondérée",
  overdueDeadlinesLabel: "en retard",
  actNow: "Agir immédiatement",
  allOnTrack: "Tout est en ordre",
  highRiskLabel: "Dossiers à haut risque (actifs)",
  noHighRisk: "Aucun dossier à haut risque ✓",
  topChancesLabel: "Meilleures opportunités (actives)",
  noTopChancesText: "Aucun dossier à pronostic élevé",
  nextDeadlinesLabel: "Prochains délais",
  showAllLink: "Tout afficher →",
  noOpenDeadlinesText: "Aucun délai ouvert ✓",
  allMandatesLabel: "Tous les dossiers",
  entriesLabel: (n) => `${n} entrées`,
  tableHeaderCase: "Dossier",
  tableHeaderCourt: "Tribunal",
  tableHeaderClaimValue: "Valeur du litige",
  tableHeaderStatus: "Statut",
  casesLabelShort: "Dossiers",

  // RichterProfile
  judgeProfilesTitle: "Profils de juges",
  profilesSub: (n) => `${n} profils · Expériences & analyse tactique IA`,
  addJudgeBtn: "+ Juge",
  editProfileTitle: "Modifier le profil",
  newProfileTitle: "Nouveau profil de juge",
  namePlaceholder: "Nom *",
  courtPlaceholder: "Tribunal *",
  chamberPlaceholder: "Chambre / Formation",
  plaintiffRateLabel: "Taux demandeur %",
  settlementRateLabel: "Taux de règlement %",
  avgDurationLabel: "Durée moy. (mois)",
  totalRulingsLabel: "Décisions totales",
  knownForPlaceholder: "Connu pour...",
  notesPlaceholder: "Notes",
  linkToCase: "Lier à un dossier",
  selectCasePlaceholder: "Sélectionner un dossier...",
  detailsAI: "Détails & IA",
  noProfilesTitle: "Aucun profil de juge",
  noProfilesSub: "Cliquez sur « + Juge » pour créer un profil",
  plaintiffRateBar: "Taux demandeur",
  settlementRateBar: "Taux de règlement",
  avgMonthsSuffix: "mois moy.",
  rulingsLabelShort: "Décisions",
  experiencesLabelShort: "Expériences",
  kiAnalysisExists: "✓ Analyse IA disponible",

  // RichterDetail
  backToOverview: "Retour à la liste",
  experiencesSection: "Expériences du cabinet",
  addExperience: "Expérience",
  dateLabel: "Date",
  authorLabel: "Auteur / Avocat",
  caseContextLabel: "Contexte du dossier (optionnel)",
  settlementReadiness: "Disposition au règlement",
  decisionSpeed: "Rapidité de décision",
  expertiseLabel: "Expertise",
  experienceReport: "Rapport d'expérience *",
  noExperiencesYet: "Aucune expérience documentée.",
  addFirstExperience: "Ajoutez la première expérience.",
  kiTacticsTitle: "Analyse tactique IA",
  reanalyzeBtn: "Ré-analyser",
  startAnalysisBtn: "Démarrer l'analyse",
  analyzingBtn: "Analyse en cours...",
  kiAnalysisHint: "Démarrez l'analyse IA pour obtenir des recommandations tactiques basées sur le profil et les expériences du cabinet.",
  lastAnalysis: "Dernière analyse",
  kiCreditWarning: "⚠️ Cette analyse utilise Gemini Pro avec recherche internet (plus de crédits IA)",
  summaryLabel: "📊 Résumé",
  foundRulingsLabel: "🔍 Décisions & jugements trouvés",
  argumentationPatternsLabel: "🧠 Schémas d'argumentation typiques",
  preferredNormsLabel: "§ Normes juridiques préférées",
  argumentStanceLabel: "⚖️ Position sur les types d'arguments",
  preferredMotionsLabel: "📋 Types de requêtes préférés",
  damageRangeLabel: "💶 Fourchette de dommages-intérêts",
  evidenceHandlingLabel: "📜 Gestion des preuves",
  plaintiffStrengthsLabel: "✅ Points forts pour le demandeur",
  plaintiffRisksLabel: "⚠️ Risques pour le demandeur",
  doLabel: "👍 À FAIRE",
  dontLabel: "👎 À ÉVITER",
  tacticalTipsLabel: "💡 Conseils tactiques",
  settlementStrategyLabel: "🤝 Stratégie de règlement",
  timingLabel: "⏰ Timing",
  overallAssessmentLabel: "🎯 Évaluation globale",
  anonLabel: "Anonyme",
  settlementBar: "Règlement",
  speedBar: "Rapidité",
  resultLabel: "Résultat",
  sourceLabel: "Source",
  parametersLabel: "Paramètres",
  successRateLabel: "Taux de succès",
  typicalRangeLabel: "Fourchette typique",
  factorsLabel: "Facteurs",
  specialFeaturesLabel: "Particularités",
  stanceLabel: "Position",
  reasonLabel: "Justification",

  // Zeitleiste
  timelineTitle: "Calendrier des délais",
  iCalExport: "Exporter iCal",
  filterAll: "Tous",
  filterOpen: "Ouverts",
  filterCritical: "⚠ Critiques",
  filterCompleted: "Terminés",
  noDeadlinesFound: "Aucun délai trouvé",
  openStatusLabel: "ouvert",
  criticalStatusLabel: "critique (≤14 jours)",
  doneStatus: "Terminé",
  missedStatus: "Manqué",

  // PlattformAgent
  newSession: "+ Nouvelle session",
  sessionsLabel: "Sessions",
  noSessionsYet: "Aucune session",
  platformAgentTitle: "Optimiseur de plateforme",
  platformAgentDesc: "L'agent IA analyse les données de votre cabinet, identifie les lacunes et met en œuvre des améliorations directement.",
  nextTaskPlaceholder: "Prochaine tâche pour l'agent…",
  customTaskPlaceholder: "Saisir une tâche personnalisée…",
  agentNote: "L'agent peut créer et modifier des profils de juges, des arguments et des délais directement.",

  module: [
    { category: "Assistant IA", title: "Chat assistant dossier", description: "Analyse IA conversationnelle de vos dossiers" },
    { category: "Gestion des dossiers", title: "Tableau de bord Lexara", description: "Tous les dossiers en un coup d'œil" },
    { category: "Profils de personnes", title: "Profils de juges", description: "Expériences, statistiques & analyse tactique IA" },
    { category: "Agent IA", title: "Agent de plateforme", description: "Agent autonome d'optimisation de la plateforme" },
    { category: "Cockpit", title: "Cockpit cabinet", description: "Indicateurs de risque, portefeuille et délais" },
    { category: "Analytique", title: "Analytique cabinet", description: "Visualisation de tous les indicateurs de dossiers" },
    { category: "Stratégie & Psycho-Analyse", title: "Sun Tzu × Machiavel", description: "48 Lois du Pouvoir · Chemin stratégique & évaluation des risques" },
  ],
};

const TEXTS = {
  DE: DE_TEXT, AT: DE_TEXT, CH: DE_TEXT, LI: DE_TEXT,
  EN: EN_TEXT, US: EN_TEXT, SE: EN_TEXT, NO: EN_TEXT, DK: EN_TEXT, FI: EN_TEXT,
  LU: FR_TEXT, FR: FR_TEXT,
};

export function getT(jurisdiction) {
  return TEXTS[jurisdiction] || DE_TEXT;
}

export function getTByLanguage(lang) {
  if (lang === "EN") return EN_TEXT;
  if (lang === "FR") return FR_TEXT;
  return DE_TEXT;
}